#!/bin/sh                              
#Test run script    
                  
make run_sim                       \
OPT="+UVM_VERBOSITY=UVM_MEDIUM     \
+inp_num_cboids=20               \
+watchdog_timer=2000                  \
+minlength=5 \
+maxlength=10 \
+minwidth=5 \
+maxwidth=10 \
+minheight=5 \
+maxheight=10 \
"                                  \
GUI=0         
                   
