#!/bin/sh                              
#Test run script    
                  
make run_sim                       \
OPT="+UVM_VERBOSITY=UVM_MEDIUM     \
+inp_num_cboids=20               \
+watchdog_timer=2000                  \
"                                  \
GUI=0         
                   
